# -*- coding: utf-8 -*-
"""trainingYOLO11n.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UIJltHTjL6BhstWn-j2R_PVkzbQ7zlYT
"""

# # %% [markdown]
# # # rescue-swarm · YOLO11n human-detector pipeline on Google Colab
# #
# # End-to-end reproduction of the local training pipeline (`training/*.py`) in
# # Colab, with the **local VisDrone2019-DET copy replaced by the remote
# # dataset** (Ultralytics' asset mirror of the official release zips).
# #
# # | Stage | Local script | Notebook cell |
# # |---|---|---|
# # | Dataset download | *(manual, local disk)* | VisDrone from remote repo |
# # | VisDrone → YOLO conversion | `training/prepare_dataset.py` | Prepare dataset |
# # | Training (2-stage fine-tune) | `training/train.py` | Stage 1 / Stage 2 |
# # | Export NCNN/ONNX int8/fp16 | `training/export.py` | Export |
# # | Video inference + FPS | `training/inference.py` | Inference |
# # | RPi 5-constrained eval | `training/eval/evaluate.py` | Accuracy / Speed |
# #
# # Usage:
# # 1. Colab: `Runtime → Change runtime type → GPU` (T4 is enough).
# # 2. This file is [jupytext percent format](https://jupytext.readthedocs.io).
# #    Convert and upload, or paste cells manually:
# #    `pip install jupytext && jupytext --to ipynb notebooks/notebook.py`
# # 3. Set `REPO_URL` below to your fork of `rescue-swarm`, then `Run all`.
# #
# # The notebook clones the repo and drives its real scripts, so behavior stays
# # identical to local runs; only data sourcing and runtime change.

# # %%
# # --- Configuration ----------------------------------------------------------
# REPO_URL = "https://github.com/<your-user>/rescue-swarm.git"  # set to your fork
# BRANCH = "main"
# ROOT = "/content/rescue-swarm"

# USE_DRIVE = False          # True -> mount Drive and persist runs/ there
# EPOCHS_STAGE1 = 100        # frozen-backbone fine-tune (reduce on free T4)
# EPOCHS_STAGE2 = 40         # full fine-tune with cosine LR
# IMGSZ_TRAIN = 512
# IMGSZ_EXPORT = 416         # deployment input size (RPi 5 target)

# DATA_DIR = f"{ROOT}/datasets/usable"
# DATASET_YAML = f"{DATA_DIR}/yolo-human/data.yaml"
# BEST_PT = f"{ROOT}/runs/detect/train/weights/best.pt"            # stage 1
# FINAL_PT = f"{ROOT}/runs/detect/train-stage2/weights/best.pt"    # stage 2

# if "<your-user>" in REPO_URL:
#     raise SystemExit("Set REPO_URL in this cell to your rescue-swarm git remote.")

# # %%
# # --- GPU check --------------------------------------------------------------
# # Colab must be on a GPU runtime before running anything else.
# !nvidia-smi
# import torch
# print(f"torch {torch.__version__} · CUDA available: {torch.cuda.is_available()}")

# # %%
# # --- Clone repo + install dependencies ---------------------------------------
# # Colab already ships a CUDA build of torch; we deliberately do NOT pin the
# # repo's requirements-working.txt torch version here (it would fight Colab's
# # driver/CUDA combo). Everything else comes from ultralytics + export runtimes.
# %cd /content
# !git clone --depth 1 -b {BRANCH} {REPO_URL}
# %cd {ROOT}
# %pip install -q ultralytics ncnn onnx onnxslim onnxruntime

# # %%
# # --- Optional: persist artifacts to Google Drive -----------------------------
# if USE_DRIVE:
#     from google.colab import drive
#     drive.mount("/content/drive")
#     DRIVE_OUT = "/content/drive/MyDrive/rescue-swarm-runs"
# else:
#     DRIVE_OUT = None
# print(f"DRIVE_OUT = {DRIVE_OUT}")

# # %% [markdown]
# # ## Dataset · VisDrone2019-DET from the remote repo
# #
# # Instead of the local copy under `datasets/usable/VisDrone2019-DET-*`, pull
# # the official DET train/val zips from Ultralytics' asset mirror (same content
# # as the [VisDrone-Dataset releases](https://github.com/VisDrone/VisDrone-Dataset),
# # which host on Google Drive and hit quota errors in Colab). Each zip extracts
# # to `<split>/{annotations,images}` — exactly the layout
# # `prepare_dataset.py` expects.
# #
# # The converter keeps only categories 1 (pedestrian) and 2 (people), maps them
# # to class `0: human`, drops ignored regions / non-human classes, and writes
# # normalized center-x/y/w/h labels plus `data.yaml`.

# # %%
# # --- Download + unzip VisDrone2019-DET (train + val) -------------------------
# import os

# ASSETS = "https://github.com/ultralytics/assets/releases/download/v0.0.0"
# os.makedirs(DATA_DIR, exist_ok=True)
# %cd {DATA_DIR}
# for split in ("train", "val"):
#     !wget -q --show-progress {ASSETS}/VisDrone2019-DET-{split}.zip
#     !unzip -qo VisDrone2019-DET-{split}.zip && rm VisDrone2019-DET-{split}.zip

# for split in ("train", "val"):
#     d = f"{DATA_DIR}/VisDrone2019-DET-{split}"
#     n_img = len(os.listdir(f"{d}/images"))
#     n_ann = len(os.listdir(f"{d}/annotations"))
#     print(f"[download] {d}: {n_img} images, {n_ann} annotations")
# assert all(
#     os.path.isdir(f"{DATA_DIR}/VisDrone2019-DET-{s}/{sub}")
#     for s in ("train", "val") for sub in ("images", "annotations")
# ), "VisDrone extraction failed — check the wget output above."

# # %%
# # --- Convert to single-class YOLO dataset ------------------------------------
# %cd {ROOT}
# !python training/prepare_dataset.py \
#     --train {DATA_DIR}/VisDrone2019-DET-train \
#     --val   {DATA_DIR}/VisDrone2019-DET-val \
#     --out   {DATA_DIR}/yolo-human

# !cat {DATASET_YAML}
# print("train images:", len(os.listdir(f"{DATA_DIR}/yolo-human/train/images")))

# # %% [markdown]
# # ## Training · two-stage fine-tune
# #
# # Same recipe as the repo docs:
# #
# # * **Stage 1** — COCO backbone frozen (`freeze 10`), fast high-quality transfer.
# # * **Stage 2** — full net unfrozen (`freeze 0`) with cosine LR, warm-started
# #   from Stage 1's `best.pt`.
# #
# # Free-tier T4: Stage 1 @100 epochs takes a few hours. For a quick end-to-end
# # dry run replace the command below with:
# # `python training/train.py --epochs 3 --fraction 0.2 --profile`

# # %%
# # --- Stage 1: frozen-backbone fine-tune ---------------------------------------
# %cd {ROOT}
# !python training/train.py \
#     --data {DATASET_YAML} \
#     --epochs {EPOCHS_STAGE1} --batch -1 --imgsz {IMGSZ_TRAIN} \
#     --freeze 10 --single-cls --workers 8

# # %%
# # --- Stage 2: full fine-tune with cosine LR -----------------------------------
# # NOTE: --name train-stage2 (not the default "train"): train.py purges its
# # target run dir before loading weights, so reusing runs/detect/train would
# # delete the Stage-1 best.pt we are about to load.
# %cd {ROOT}
# !python training/train.py \
#     --data {DATASET_YAML} \
#     --weights {BEST_PT} \
#     --freeze 0 --epochs {EPOCHS_STAGE2} --imgsz {IMGSZ_TRAIN} \
#     --single-cls --cos-lr --workers 8 \
#     --project runs/detect --name train-stage2

# import os
# if not os.path.isfile(FINAL_PT):           # Stage 2 skipped? fall back
#     FINAL_PT = BEST_PT
# print(f"FINAL_PT = {FINAL_PT}")

# # %%
# # --- Training curves ----------------------------------------------------------
# from IPython.display import Image as IPyImage, display
# run_dir = os.path.dirname(FINAL_PT)  # .../weights
# run_dir = os.path.dirname(run_dir)
# display(IPyImage(filename=f"{run_dir}/results.png"))
# display(IPyImage(filename=f"{run_dir}/confusion_matrix.png"))

# # %% [markdown]
# # ## Export · NCNN / ONNX for the Raspberry Pi 5
# #
# # Recommended deployment path is NCNN fp16 or int8 (ARM NEON); ONNX int8 is
# # the secondary option. Exports are written next to the weights:
# # `best_ncnn_model/`, `best.onnx`.

# # %%
# # --- Export fp16 + int8 --------------------------------------------------------
# NCNN_FP16_DIR = os.path.splitext(FINAL_PT)[0] + "_ncnn_model"

# !python training/export.py --model {FINAL_PT} --format ncnn --imgsz {IMGSZ_EXPORT} --half
# !python training/export.py --model {FINAL_PT} --format ncnn --imgsz {IMGSZ_EXPORT} --int8 --data {DATASET_YAML}
# !python training/export.py --model {FINAL_PT} --format onnx --imgsz {IMGSZ_EXPORT} --int8 --data {DATASET_YAML}

# print("exports beside:", os.path.dirname(FINAL_PT))
# print(NCNN_FP16_DIR, "->", os.path.isdir(NCNN_FP16_DIR))

# # %% [markdown]
# # ## Inference
# #
# # Spot-check predictions on val frames, then (optionally) run the video FPS
# # runner on your own drone clip.

# # %%
# # --- Qualitative check on validation frames ------------------------------------
# import glob, cv2, matplotlib.pyplot as plt
# from ultralytics import YOLO

# model = YOLO(FINAL_PT)
# samples = sorted(glob.glob(f"{DATA_DIR}/yolo-human/val/images/*.jpg"))[:6]
# results = model.predict(samples, imgsz=IMGSZ_EXPORT, conf=0.35, iou=0.45, verbose=False)

# fig, axes = plt.subplots(2, 3, figsize=(16, 9))
# for ax, r in zip(axes.flat, results):
#     ax.imshow(cv2.cvtColor(r.plot(), cv2.COLOR_BGR2RGB))
#     ax.axis("off")
# plt.tight_layout()
# plt.show()

# # %%
# # --- Optional: video inference (upload a clip or point at Drive) ----------------
# VIDEO_PATH = ""  # e.g. "/content/drive/MyDrive/drone.mp4"; leave "" to skip

# if VIDEO_PATH:
#     !python training/inference.py --model {FINAL_PT} \
#         --input {VIDEO_PATH} --output annotated.mp4 --imgsz {IMGSZ_EXPORT}

# # %% [markdown]
# # ## Evaluation · Raspberry Pi 5 constraints
# #
# # `evaluate.py` pins CPU-only execution, 4 threads, ~4 GB RSS and scales raw
# # FPS by `--rpi-factor 0.55` to estimate Pi 5 throughput. On Colab the accuracy
# # pass runs on CPU, so expect it to take several minutes.

# # %%
# # --- Accuracy: mAP50 / mAP50-95 on the val split ---------------------------------
# !python training/eval/evaluate.py accuracy \
#     --model {FINAL_PT} --data {DATASET_YAML} \
#     --imgsz {IMGSZ_EXPORT} --threads 4

# # %%
# # --- Speed sweep: synthesize a test clip from val frames, then benchmark --------
# import cv2

# SAMPLE_VIDEO = "/content/sample_drone.mp4"
# frame_files = sorted(glob.glob(f"{DATA_DIR}/yolo-human/val/images/*.jpg"))[:120]
# if frame_files:
#     w, h = 1280, 720
#     vw = cv2.VideoWriter(SAMPLE_VIDEO, cv2.VideoWriter_fourcc(*"mp4v"), 30, (w, h))
#     for f in frame_files:
#         im = cv2.imread(f)
#         if im is not None:
#             vw.write(cv2.resize(im, (w, h)))
#     vw.release()
#     print(f"[speed] synthesized {SAMPLE_VIDEO} from {len(frame_files)} val frames")

#     models = [FINAL_PT] + ([NCNN_FP16_DIR] if os.path.isdir(NCNN_FP16_DIR) else [])
#     model_args = " ".join(models)
#     %cd {ROOT}
#     !python training/eval/evaluate.py speed \
#         --models {model_args} \
#         --video {SAMPLE_VIDEO} --imgsz 640,416,352 --threads 4
# else:
#     print("[speed] no val frames found — run the dataset cells first")

# # %%
# # --- Collect artifacts -----------------------------------------------------------
# import shutil

# artifacts = [FINAL_PT, f"{os.path.splitext(FINAL_PT)[0]}.onnx"]
# if os.path.isdir(NCNN_FP16_DIR):
#     zip_base = shutil.make_archive("/content/best_ncnn_model", "zip",
#                                    os.path.dirname(NCNN_FP16_DIR),
#                                    os.path.basename(NCNN_FP16_DIR))
#     artifacts.append(zip_base)

# print("Artifacts ready:")
# for a in artifacts:
#     size = os.path.getsize(a) / 1e6 if os.path.isfile(a) else float("nan")
#     print(f"  {a} ({size:.1f} MB)" if size == size else f"  {a}/")

# if DRIVE_OUT:
#     os.makedirs(DRIVE_OUT, exist_ok=True)
#     for a in artifacts:
#         dest = os.path.join(DRIVE_OUT, os.path.basename(a).replace(".zip", ""))
#         (shutil.copytree if os.path.isdir(a) else shutil.copy2)(a, dest)
#     print(f"Copied to {DRIVE_OUT}")

# # from google.colab import files
# # files.download(FINAL_PT)

# # %% [markdown]
# # ## Next steps
# #
# # 1. Copy `best_ncnn_model/` (or `best.onnx`) to the Raspberry Pi 5.
# # 2. Run on-device inference:
# #    `python training/inference.py --model best_ncnn_model --input drone.mp4 --output out.mp4 --imgsz 416`
# # 3. Compare on-Pi FPS against the ≥15 FPS target using the numbers above.

"""# # rescue-swarm · YOLO11n human-detector pipeline on Google Colab
#
# End-to-end reproduction of the local training pipeline (`training/*.py`) in
# Colab, with the **local VisDrone2019-DET copy replaced by the remote
# dataset** (Ultralytics' asset mirror of the official release zips).
#
# | Stage | Local script | Notebook cell |
# |---|---|---|
# | Dataset download | *(manual, local disk)* | VisDrone from remote repo |
# | VisDrone → YOLO conversion | `training/prepare_dataset.py` | Prepare dataset |
# | Training (2-stage fine-tune) | `training/train.py` | Stage 1 / Stage 2 |
# | Export NCNN/ONNX int8/fp16 | `training/export.py` | Export |
# | Video inference + FPS | `training/inference.py` | Inference |
# | RPi 5-constrained eval | `training/eval/evaluate.py` | Accuracy / Speed |
#
# Usage:
# 1. Colab: `Runtime → Change runtime type → GPU` (T4 is enough).
# 2. Set `REPO_URL` below to your fork of `rescue-swarm`, then `Run all`.
"""

# --- Configuration ----------------------------------------------------------
REPO_URL = "https://github.com/TheGoodDevil00/model-training"  # set to your fork
BRANCH = "main"
# Updated ROOT to match the repository name
ROOT = "/content/model-training"

USE_DRIVE = False          # True -> mount Drive and persist runs/ there
EPOCHS_STAGE1 = 100        # frozen-backbone fine-tune (reduce on free T4)
EPOCHS_STAGE2 = 40         # full fine-tune with cosine LR
IMGSZ_TRAIN = 1080
IMGSZ_EXPORT = 416         # deployment input size (RPi 5 target)

DATA_DIR = f"{ROOT}/datasets/usable"
DATASET_YAML = f"{DATA_DIR}/yolo-human/data.yaml"
BEST_PT = f"{ROOT}/runs/detect/train/weights/best.pt"            # stage 1
FINAL_PT = f"{ROOT}/runs/detect/train-stage2/weights/best.pt"    # stage 2

if "<your-user>" in REPO_URL:
    print("WARNING: Set REPO_URL in this cell to your rescue-swarm git remote.")

# --- GPU check --------------------------------------------------------------
!nvidia-smi
import torch
print(f"torch {torch.__version__} · CUDA available: {torch.cuda.is_available()}")

# Commented out IPython magic to ensure Python compatibility.
# --- Clone repo + install dependencies ---------------------------------------
# %cd /content
import os
if not os.path.exists(ROOT):
    !git clone --depth 1 -b {BRANCH} {REPO_URL}
else:
    print(f"{ROOT} already exists, skipping clone.")

# %cd {ROOT}
# %pip install -q ultralytics ncnn onnx onnxslim onnxruntime

"""## Dataset · VisDrone2019-DET
Pulling official DET train/val zips and converting to YOLO format.
"""

# Commented out IPython magic to ensure Python compatibility.
import os
ASSETS = "https://github.com/ultralytics/assets/releases/download/v0.0.0"
os.makedirs(DATA_DIR, exist_ok=True)
# %cd {DATA_DIR}
for split in ("train", "val"):
    !wget -q --show-progress {ASSETS}/VisDrone2019-DET-{split}.zip
    !unzip -qo VisDrone2019-DET-{split}.zip && rm VisDrone2019-DET-{split}.zip

# Commented out IPython magic to ensure Python compatibility.
# --- Convert to single-class YOLO dataset ------------------------------------
# %cd {ROOT}
!python training/prepare_dataset.py \
    --train {DATA_DIR}/VisDrone2019-DET-train \
    --val   {DATA_DIR}/VisDrone2019-DET-val \
    --out   {DATA_DIR}/yolo-human

"""## Training
Stage 1: Frozen backbone. Stage 2: Full fine-tune.
"""

!python training/train.py \
    --data {DATASET_YAML} \
    --epochs {EPOCHS_STAGE1} --batch -1 --imgsz {IMGSZ_TRAIN} \
    --freeze 10 --single-cls --workers 8

!python training/train.py \
    --data {DATASET_YAML} \
    --weights {BEST_PT} \
    --freeze 0 --epochs {EPOCHS_STAGE2} --imgsz {IMGSZ_TRAIN} \
    --single-cls --cos-lr --workers 8 \
    --project runs/detect --name train-stage2

"""## Export & Evaluation
Export to NCNN/ONNX and evaluate on CPU to simulate RPi 5 constraints.
"""

!python training/export.py --model {FINAL_PT} --format ncnn --imgsz {IMGSZ_EXPORT} --half
!python training/export.py --model {FINAL_PT} --format ncnn --imgsz {IMGSZ_EXPORT} --int8 --data {DATASET_YAML}

!python training/eval/evaluate.py accuracy \
    --model {FINAL_PT} --data {DATASET_YAML} \
    --imgsz {IMGSZ_EXPORT} --threads 4